version: '3.8'

services:
  webapp:
    image: mitali/web_app:1.0
    build: .
    ports:
      - "3111:3111"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3111/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s